### PR TITLE
Add a few abbrevs

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by Malabarba** [comment]
I'm sorry I didn't see this sooner. Github just failed to notify me for some reason. 
It's hard to see here which abbrevs are being defined, because the diff shows the entire file. (that's what I get for creating the file under Windows).

However, after your abel post I did look into your file and add a few abbrevs from there. So it may be that the abbrevs suggested here are already included.

**Comment by abo-abo** [comment]
If you set `ediff-diff-options` to `"-w"`, it will be very easy to see
the diff.

Currently, I'm on the fence about extending `abel`.
I don't know if adding more abbrevs will make it better or worse.
Same thing with removing. Hoping to see something from you that solves everything:)

**Comment by Malabarba** [comment]
Why do you feel it might be worse? 

One thing that really bothers me right now is that it expands inside let forms. But that's a quick fix in the predicate.

**Comment by abo-abo** [comment]
> Why do you feel it might be worse?

It can be worse since I stop to think about if I have an abbrev for
what I want, and what it is.  Sometimes it would be just faster to
type the thing out.

It's similar to <kbd>7j</kbd> in `vi`: sure it's efficient, but it's mostly
just better to hold <kbd>j</kbd>, go down even a bit too much, and refine with <kbd>k</kbd>.

**Comment by Malabarba** [comment]
After a shamefully long delay, I've finally gone through these abbrevs and added the ones that were possible. Thanks, for the suggestions.

**Comment by abo-abo** [comment]
I still haven't figured out those abbrevs:)
I have them on and they annoy me from time to time, but I never actually use them: `company-mode` is just much better.

**Comment by Malabarba** [comment]
Maybe it's just about different workflows. :-)
The abbrevs take 2-4 keys for me, whereas completion usually takes around 4-8.
But I do mess up a lot when completing :P

**Pull request closed without merging**
